# Generated by Django 4.2.4 on 2023-08-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_author_snippet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
